FROM jtim/centos6-jdk8

LABEL maintainer=tonyss5396@gamil.com

RUN useradd 7thonline && \
    usermod --password 7thonline 7thonline && \
    mkdir -p /usr/local/7thonline && \
    chown -R 7thonline /usr/local/7thonline && \
    chmod -R 775 /usr/local/7thonline && \
    cd /usr/local/7thonline && \
    mv /usr/java/jdk1.8.0_121/ Java/ && \
    wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.12/bin/apache-tomcat-8.5.12.tar.gz && \
    tar zxvf apache-tomcat-8.5.12.tar.gz && \
    rm -f apache-tomcat-8.5.12.tar.gz

ENV JAVA_HOME=/usr/local/7thonline/Java/ && \
    PATH=$PATH:JAVA_HOME=/usr/local/7thonline/Java/bin

RUN cd /usr/local/7thonline/apache-tomcat-8.5.12/conf
ENTRYPOINT [ "/bin/bash" ]
